export enum ESharedInputType {
  DESTINATIONS_FLIGHTS = 'DESTINATIONS_FLIGHTS',
  ORIGINS_FLIGHTS = 'ORIGINS_FLIGHTS',
  DESTINATIONS_HOTELS = 'DESTINATIONS_HOTELS',

   // ⭐ חדש
  PICKER_DATES = 'PICKER_DATES'
}
