export enum ESharedInputType {
  DESTINATIONS_FLIGHTS = 'DESTINATIONS_FLIGHTS',
  ORIGINS_FLIGHTS = 'ORIGINS_FLIGHTS',
  PASSANGERS_FLIGHTS = 'PASSANGERS_FLIGHTS',
  PICKER_DATES = 'PICKER_DATES',
  HOTELS_DESTINATION = 'HOTELS_DESTINATION'
}
