export enum ESharedInputType {
  DESTINATIONS_FLIGHTS = 'DESTINATIONS_FLIGHTS',
  ORIGINS_FLIGHTS = 'ORIGINS_FLIGHTS',
  DESTINATIONS_HOTELS = 'DESTINATIONS_HOTELS',
  PASSANGERS_FLIGHTS = 'PASSANGERS_FLIGHTS',
   // ⭐ חדש
  PICKER_DATES = 'PICKER_DATES' 
}
