export enum ETypeSearchEngine {
  FLIGHTS = 'FLIGHTS',
  HOTELS_ABROAD = 'HOTELS_ABROAD',
  FLIGHTS_MULTI_DESTINATIONS = 'FLIGHTS_MULTI_DESTINATIONS',
  DOMESTIC_VACATIONS = 'DOMESTIC_VACATIONS',
  FLIGHTS_TO_EILAT = 'FLIGHTS_TO_EILAT',
  FLIGHTS_AND_HOTELS_TO_EILAT = 'FLIGHTS_AND_HOTELS_TO_EILAT',
  SPORT = 'SPORT',
  ORGANIZED_TOURS = 'ORGANIZED_TOURS'
}
